#pelicanconf.py.old
'EXTRA_PATH_METADATA': {'extra/custom.css': {'path': 'static/css/custom.css'},
                         'extra/custom.js': {'path': 'static/js/custom.js'}},
 'FAVICON': 'images/sunlight.png',
 'FEED_ALL_ATOM': None,
 'FEED_DOMAIN': 'localhost:8000',
 'FEED_MAX_ITEMS': '',
 'FILENAME_METADATA': '(?P<date>\\d{4}-\\d{2}-\\d{2}).*',
 'FORMATTED_FIELDS': ['summary'],
 'GZIP_CACHE': True,
 'I18N_TEMPLATES_LANG': 'en',
 'IGNORE_FILES': ['.#*', '.ipynb_checkpoints'],
 'INDEX_SAVE_AS': 'index.html',
 'INTRASITE_LINK_REGEX': '[{|](?P<what>.*?)[|}]',
 'JINJA_ENVIRONMENT': {'extensions': ['jinja2.ext.i18n'],
                       'lstrip_blocks': True,
                       'trim_blocks': True},
 'JINJA_FILTERS': {},
 'LINKS': (('Pelican', 'http://getpelican.com/'),
           ('Python.org', 'http://python.org/'),
           ('Jinja2', 'http://jinja.pocoo.org/'),
           ('Learn Enough to be dangerous',
            'https://www.learnenough.com/dev-environment-tutorial#sec-native_os_setup'),
           ('Full Stack Python', 'https://www.fullstackpython.com/'),
           ('How I Built This Site',
            'https://pythonforundergradengineers.com/how-i-built-this-site-1.html')),
 'LOAD_CONTENT_CACHE': False,
 'LOCALE': [''],
 'LOG_FILTER': [],
 'MARKDOWN': {'extension_configs': {'markdown.extensions.codehilite': {'css_class': 'highlight'},
                                    'markdown.extensions.extra': {},
                                    'markdown.extensions.meta': {}},
              'extensions': [<liquid_tags.mdx_liquid_tags.LiquidTags object at 0x10b6e67f0>,
                             <render_math.pelican_mathjax_markdown_extension.PelicanMathJaxExtension object at 0x10b6f0630>],
              'output_format': 'html5'},
 'MARKUP': ('md', 'ipynb'),
 'MENUITEMS': [('Posts', '/water/articles/2018/index.html'),
               ('Categories', '/categories.html')],
 'MONTH_ARCHIVE_SAVE_AS': 'posts/{date:%Y}/{date:%b}/index.html',
 'MONTH_ARCHIVE_URL': '',
 'NEWEST_FIRST_ARCHIVES': True,
 'OUTPUT_PATH': 'output',
 'OUTPUT_RETENTION': [],
 'OUTPUT_SOURCES': False,
 'OUTPUT_SOURCES_EXTENSION': '.text',
 'PAGE_EXCLUDES': ['articles'],
 'PAGE_LANG_SAVE_AS': 'pages/{slug}-{lang}.html',
 'PAGE_LANG_URL': 'pages/{slug}-{lang}.html',
 'PAGE_ORDER_BY': 'basename',
 'PAGE_PATHS': ['pages'],
 'PAGE_SAVE_AS': 'pages/{slug}/index.html',
 'PAGE_TRANSLATION_ID': 'slug',
 'PAGE_URL': 'pages/{slug}/',
 'PAGINATED_TEMPLATES': {'author': None,
                         'category': None,
                         'index': None,
                         'tag': None},
 'PAGINATION_PATTERNS': [PaginationRule(min_page=1, URL='{name}{extension}', SAVE_AS='{name}{extension}'),
                         PaginationRule(min_page=2, URL='{name}{number}{extension}', SAVE_AS='{name}{number}{extension}')],
 'PATH': '/Users/johngage/Documents/blog/content',
 'PATH_METADATA': '',
 'PELICAN_CLASS': 'pelican.Pelican',
 'PLUGINS': ['neighbors',
             'series',
             'tag_cloud',
             'liquid_tags.img',
             'liquid_tags.video',
             'liquid_tags.youtube',
             'liquid_tags.notebook',
             'liquid_tags.vimeo',
             'liquid_tags.include_code',
             'related_posts',
             'render_math',
             'tipue_search',
             'pelican-ipynb.markup',
             'sitemap',
             'better_codeblock_line_numbering'],
 'PLUGIN_PATHS': ['/Users/johngage/Documents/blog/pelican-plugins'],
 'PORT': 8000,
 'PYGMENTS_RST_OPTIONS': {},
 'READERS': {},
 'RECENT_POST_COUNT': 4,
 'RELATIVE_URLS': False,
 'REVERSE_CATEGORY_ORDER': False,
 'RSS_FEED_SUMMARY_ONLY': True,
 'SIDEBAR_EMAIL': 'john.gage@gmail.com',
 'SIDEBAR_IMAGES': ['/images/sunlight.png'],
 'SIDEBAR_IMAGES_HEADER': 'My Images',
 'SIDEBAR_NAME': 'AUTHOR',
 'SIDEBAR_TAGS': ['Califoria Schools'],
 'SITEMAP': {'changefreqs': {'articles': 'monthly',
                             'indexes': 'daily',
                             'pages': 'monthly'},
             'format': 'xml',
             'priorities': {'articles': 0.5, 'indexes': 0.5, 'pages': 0.5}},
 'SITENAME': 'Water, Power, Network',
 'SITESUBTITLE': 'City Critical Infrastructure',
 'SITEURL': 'localhost:8000',
 'SLUGIFY_SOURCE': 'title',
 'SLUG_REGEX_SUBSTITUTIONS': [('[^\\w\\s-]', ''),
                              ('(?u)\\A\\s*', ''),
                              ('(?u)\\s*\\Z', ''),
                              ('[-\\s]+', '-')],
 'SOCIAL': (('Berkeley', 'http://berkeley.edu'),
            ('Berkeley Institute of Data Sciences', 'http://berkeley.edu'),
            ('Time', 'http://timeanddate.com')),
 'STATIC_CHECK_IF_MODIFIED': False,
 'STATIC_CREATE_LINKS': False,
 'STATIC_EXCLUDES': [],
 'STATIC_EXCLUDE_SOURCES': True,
 'STATIC_PATHS': ['images', 'data', 'publications', 'extra'],
 'STATIC_SAVE_AS': '{path}',
 'STATIC_URL': '{path}',
 'SUMMARY_MAX_LENGTH': 50,
 'TAG_CLOUD_BADGE': False,
 'TAG_CLOUD_MAX_ITEMS': 100,
 'TAG_CLOUD_SORTING': 'random',
 'TAG_CLOUD_STEPS': 4,
 'TAG_SAVE_AS': 'tag/{slug}.html',
 'TAG_URL': 'tag/{slug}.html',
 'TEMPLATE_EXTENSIONS': ['.html'],
 'TEMPLATE_PAGES': {},
 'THEME': '/Users/johngage/Documents/blog/pelican-themes/pelican-bootstrap3',
 'THEME_STATIC_DIR': 'theme',
 'THEME_STATIC_PATHS': ['static'],
 'THEME_TEMPLATES_OVERRIDES': [],
 'TIMEZONE': 'America/Los_Angeles',
 'TRANSLATION_FEED_ATOM': None,
 'TYPOGRIFY': False,
 'TYPOGRIFY_IGNORE_TAGS': [],
 'USE_FOLDER_AS_CATEGORY': False,
 'WITH_FUTURE_DATES': True,
 'WRITE_SELECTED': [],
 'YEAR_ARCHIVE_SAVE_AS': 'posts/{date:%Y}/index.html',
 'YEAR_ARCHIVE_URL': ''}
